apiVersion: v2
name: k8s-gateway
description: A fork of the k8s_gateway CoreDNS plugin with added functionalities
type: application
version: 3.4.0
appVersion: 0.9.0
maintainers:
  - email: guillaume@pinax.network
    name: Guillaume
