name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Linting is in a separate job because golangci-lint is quite slow when
  # running it in cold-start mode.
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          args: --timeout=5m0s

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.22.x
      - uses: actions/checkout@v2
      - run: make test
